Feat/GitHub commit dataset
nomic-ai/cookbook pull request #7
Opened 2024-06-20 15:40 UTC by abhisomala

creates csv and makes atlas map using github repo url

2024-06-20 18:27 UTC, AndriyMulyar requested changes

2024-06-20 18:27 UTC, AndriyMulyar commented on maps/github_commits.py
> +    repo_url = input("URL of Github Repository: ")
You should use python tmpdirectory for this!
https://docs.python.org/3/library/tempfile.html

2024-06-20 18:27 UTC, AndriyMulyar commented on maps/github_commits.py
> +    repo_url = input("URL of Github Repository: ")
not a place on the filesystem. the tmpfile package will automatically pick the right temporary storage place on each OS.

Use a `context manager` to ensure the temp directory get's cleaned up afterwords.

2024-06-20 18:27 UTC, AndriyMulyar commented on maps/github_commits.py
> +        "github-commit-dataset",
You should try to infer this title from the github repo name

2024-06-20 18:28 UTC, AndriyMulyar commented on maps/github_commits.py
> +        "github-commit-dataset",
also, be explicit with identifier='datasetname'

2024-06-26 17:27 UTC, rguo123 commented on maps/github_commits.py
> +    repo_names = [] #still trying to figure it out - saying that there isnt enough data points (even though there is)
Nit: remove wip comments from script?
In general, may be worth cleaning up some of the code comments so formatting is consistent

2024-06-26 17:27 UTC, rguo123 commented on maps/github_commits.py
> +        indexed_field='message',  #Indexs by message
Nit: typo `indexes`

2024-06-26 17:29 UTC, rguo123 commented on maps/github_commits.py
> +def save_commits_to_csv(commits, csv_filename):
It would be nice if this was an optional step in pipeline. I think the default should be to go directly from reading in the commit history into atlas rather than having first to save it as a csv

2024-06-27 02:10 UTC, AndriyMulyar approved these changes

2024-06-27 02:16 UTC, merged